In [1]:
import pandas as pd
import sqlite3
data = {
    'org_id': [11, 22, 33, 44, 55, 66, 77, 88, 99, 111, 222, 333, 444, 555, 666, 777, 888, 999, 1111, 2222],
    'org_name': ['Company A', 'Company B', 'Company C', 'Company D', 'Company E', 'Company F', 'Company G', 'Company H', 'Company I', 'Company J', 'Company K', 'Company L', 'Company M', 'Company N', 'Company O', 'Company P', 'Company Q', 'Company R', 'Company S', 'Company T'],
    'org_code': ['BIW', 'BIX', 'BMR', 'BMW', 'BIZ', 'BNB', 'BJA', 'BJI', 'BNK', 'BNQ', 'BNY', 'BNZ', 'BJJ', 'BOA', 'BOD', 'BJM', 'BJP', 'BJR', 'BJT', 'BOK'],
    'org_status': ['renewed', 'renewed', 'not renewed', 'not renewed', 'renewed', 'not renewed', 'renewed', 'renewed', 'not renewed', 'not renewed', 'not renewed', 'not renewed', 'renewed', 'not renewed', 'not renewed', 'renewed', 'renewed', 'renewed', 'renewed', 'not renewed'],
    'org_date': ['2023-05-05 04:23', '2023-05-12 06:28', '2023-06-15 06:53', '2023-06-15 18:19', '2023-05-15 09:55', '2023-06-19 09:29', '2023-05-12 08:32', '2023-05-16 10:26', '2023-06-19 17:57', '2023-06-22 11:02', '2023-06-23 07:53', '2023-06-23 07:56', '2023-05-16 12:50', '2023-06-23 11:51', '2023-06-24 05:33', '2023-05-17 06:37', '2023-05-19 04:41', '2023-05-19 07:39', '2023-05-11 06:04', '2023-06-26 10:36'],
    'properties': [
        '{"email": "biw@gmail.com","company":"Company A","location":"Maharastra"}',
        '{"email": "bix@gmail.com","location":"Punjab","company":"Company B"}',
        '{"email": "bon@gmail.com","company":"Company C","location":"Maharastra"}',
        '{"email": "bou@gmail.com","company":"Company D","location":"Gujarat"}',
        '{"email": "biz@gmail.com","location":"Gujarat","company":"Company E"}',
        '{"email": "bov@gmail.com","company":"Company F","location":"Gujarat"}',
        '{"email": "bja@gmail.com","company":"Company G","location":"Punjab"}',
        '{"email": "bji@gmail.com","company":"Company H","location":"Gujarat"}',
        '{"email": "bow@gmail.com","company":"Company I","location":"Punjab"}',
        '{"email": "bpc@gmail.com","company":"Company J","location":"Maharastra"}',
        '{"email": "bpi@gmail.com","company":"Company K","location":"Maharastra"}',
        '{"email": "bpj@gmail.com","company":"Company L","location":"Maharastra"}',
        '{"email": "bjj@gmail.com","company":"Company M","location":"Maharastra"}',
        '{"email": "bpl@gmail.com","company":"Company N","location":"Punjab"}',
        '{"email": "bpm@gmail.com","company":"Company O","location":"Maharastra"}',
        '{"email": "bjm@gmail.com","company":"Company P","location":"Gujarat"}',
        '{"email": "bjp@gmail.com","company":"Company Q","location":"Gujarat"}',
        '{"email": "bjr@gmail.com","company":"Company R","location":"Gujarat"}',
        '{"email": "bjt@gmail.com","company":"Company S","location":"Gujarat"}',
        '{"email": "bpo@gmail.com","company":"Company T","location":"Punjab"}'
    ]
}

df = pd.DataFrame(data)

# Convert org_date column to datetime format
df['org_date'] = pd.to_datetime(df['org_date'], format='%Y-%m-%d %H:%M')
conn = sqlite3.connect(':memory:')
df.to_sql('organizations', conn, index=False, if_exists='replace')
def run_query(query):
    return pd.read_sql_query(query, conn)

(   org_id   org_name org_code org_status             org_date  \
 0      11  Company A      BIW    renewed  2023-05-05 04:23:00
 1      22  Company B      BIX    renewed  2023-05-12 06:28:00
 2      55  Company E      BIZ    renewed  2023-05-15 09:55:00
 3      77  Company G      BJA    renewed  2023-05-12 08:32:00
 4      88  Company H      BJI    renewed  2023-05-16 10:26:00
 5     444  Company M      BJJ    renewed  2023-05-16 12:50:00
 6     777  Company P      BJM    renewed  2023-05-17 06:37:00
 7     888  Company Q      BJP    renewed  2023-05-19 04:41:00
 8     999  Company R      BJR    renewed  2023-05-19 07:39:00
 9    1111  Company S      BJT    renewed  2023-05-11 06:04:00

                                           properties
 0  {"email": "biw@gmail.com","company":"Company A...
 1  {"email": "bix@gmail.com","location":"Punjab",...
 2  {"email": "biz@gmail.com","location":"Gujarat"...
 3  {"email": "bja@gmail.com","company":"Company G...
 4  {"email": "bji@gmail.com","company":"Company H...
 5  {"email": "bjj@gmail.com","company":"Company M...
 6  {"email": "bjm@gmail.com","company":"Company P...
 7  {"email": "bjp@gmail.com","company":"Company Q...
 8  {"email": "bjr@gmail.com","company":"Company R...
 9  {"email": "bjt@gmail.com","company":"Company S...  ,
     org_status  count
 0  not renewed     10
 1      renewed     10,
    org_id   org_name org_code   org_status             org_date  \
 0      44  Company D      BMW  not renewed  2023-06-15 18:19:00
 1      55  Company E      BIZ      renewed  2023-05-15 09:55:00
 2      66  Company F      BNB  not renewed  2023-06-19 09:29:00
 3      88  Company H      BJI      renewed  2023-05-16 10:26:00
 4     777  Company P      BJM      renewed  2023-05-17 06:37:00
 5     888  Company Q      BJP      renewed  2023-05-19 04:41:00
 6     999  Company R      BJR      renewed  2023-05-19 07:39:00
 7    1111  Company S      BJT      renewed  2023-05-11 06:04:00

                                           properties
 0  {"email": "bou@gmail.com","company":"Company D...
 1  {"email": "biz@gmail.com","location":"Gujarat"...
 2  {"email": "bov@gmail.com","company":"Company F...
 3  {"email": "bji@gmail.com","company":"Company H...
 4  {"email": "bjm@gmail.com","company":"Company P...
 5  {"email": "bjp@gmail.com","company":"Company Q...
 6  {"email": "bjr@gmail.com","company":"Company R...
 7  {"email": "bjt@gmail.com","company":"Company S...  )

In [3]:
# 1. Get all organizations that have renewed their subscription
query1 = "SELECT * FROM organizations WHERE org_status = 'renewed'"
renewed_orgs = run_query(query1)
renewed_orgs

,org_id,org_name,org_code,org_status,org_date,properties
0,11,Company A,BIW,renewed,2023-05-05 04:23:00,"{""email"": ""biw@gmail.com"",""company"":""Company A..."
1,22,Company B,BIX,renewed,2023-05-12 06:28:00,"{""email"": ""bix@gmail.com"",""location"":""Punjab"",..."
2,55,Company E,BIZ,renewed,2023-05-15 09:55:00,"{""email"": ""biz@gmail.com"",""location"":""Gujarat""..."
3,77,Company G,BJA,renewed,2023-05-12 08:32:00,"{""email"": ""bja@gmail.com"",""company"":""Company G..."
4,88,Company H,BJI,renewed,2023-05-16 10:26:00,"{""email"": ""bji@gmail.com"",""company"":""Company H..."
5,444,Company M,BJJ,renewed,2023-05-16 12:50:00,"{""email"": ""bjj@gmail.com"",""company"":""Company M..."
6,777,Company P,BJM,renewed,2023-05-17 06:37:00,"{""email"": ""bjm@gmail.com"",""company"":""Company P..."
7,888,Company Q,BJP,renewed,2023-05-19 04:41:00,"{""email"": ""bjp@gmail.com"",""company"":""Company Q..."
8,999,Company R,BJR,renewed,2023-05-19 07:39:00,"{""email"": ""bjr@gmail.com"",""company"":""Company R..."
9,1111,Company S,BJT,renewed,2023-05-11 06:04:00,"{""email"": ""bjt@gmail.com"",""company"":""Company S..."

In [5]:
# 2. Count of organizations by status
query2 = "SELECT org_status, COUNT(*) as count FROM organizations GROUP BY org_status"
org_status_count = run_query(query2)
org_status_count

    org_status  count
0  not renewed     10
1      renewed     10

In [6]:
# 3. Get organizations located in Gujarat
query3 = "SELECT * FROM organizations WHERE properties LIKE '%Gujarat%'"
gujarat_orgs = run_query(query3)
gujarat_orgs

,org_id,org_name,org_code,org_status,org_date,properties
0,44,Company D,BMW,not renewed,2023-06-15 18:19:00,"{""email"": ""bou@gmail.com"",""company"":""Company D..."
1,55,Company E,BIZ,renewed,2023-05-15 09:55:00,"{""email"": ""biz@gmail.com"",""location"":""Gujarat""..."
2,66,Company F,BNB,not renewed,2023-06-19 09:29:00,"{""email"": ""bov@gmail.com"",""company"":""Company F..."
3,88,Company H,BJI,renewed,2023-05-16 10:26:00,"{""email"": ""bji@gmail.com"",""company"":""Company H..."
4,777,Company P,BJM,renewed,2023-05-17 06:37:00,"{""email"": ""bjm@gmail.com"",""company"":""Company P..."
5,888,Company Q,BJP,renewed,2023-05-19 04:41:00,"{""email"": ""bjp@gmail.com"",""company"":""Company Q..."
6,999,Company R,BJR,renewed,2023-05-19 07:39:00,"{""email"": ""bjr@gmail.com"",""company"":""Company R..."
7,1111,Company S,BJT,renewed,2023-05-11 06:04:00,"{""email"": ""bjt@gmail.com"",""company"":""Company S..."

In [8]:
# 4. Get organizations located in Punjab
query = "SELECT * FROM organizations WHERE properties LIKE '%\"location\":\"Punjab\"%'"
punjab_orgs = pd.read_sql_query(query, conn)
punjab_orgs

,org_id,org_name,org_code,org_status,org_date,properties
0,22,Company B,BIX,renewed,2023-05-12 06:28:00,"{""email"": ""bix@gmail.com"",""location"":""Punjab"",..."
1,77,Company G,BJA,renewed,2023-05-12 08:32:00,"{""email"": ""bja@gmail.com"",""company"":""Company G..."
2,99,Company I,BNK,not renewed,2023-06-19 17:57:00,"{""email"": ""bow@gmail.com"",""company"":""Company I..."
3,555,Company N,BOA,not renewed,2023-06-23 11:51:00,"{""email"": ""bpl@gmail.com"",""company"":""Company N..."
4,2222,Company T,BOK,not renewed,2023-06-26 10:36:00,"{""email"": ""bpo@gmail.com"",""company"":""Company T..."

In [10]:
# 5. Query to get organizations renewed between 11-05-2023 and 15-05-2023
query = """
SELECT * FROM organizations 
WHERE org_status = 'renewed' 
AND org_date BETWEEN '2023-05-11' AND '2023-05-15'
"""
renewed_orgs = pd.read_sql_query(query, conn)

# Display the results
renewed_orgs

,org_id,org_name,org_code,org_status,org_date,properties
0,22,Company B,BIX,renewed,2023-05-12 06:28:00,"{""email"": ""bix@gmail.com"",""location"":""Punjab"",..."
1,77,Company G,BJA,renewed,2023-05-12 08:32:00,"{""email"": ""bja@gmail.com"",""company"":""Company G..."
2,1111,Company S,BJT,renewed,2023-05-11 06:04:00,"{""email"": ""bjt@gmail.com"",""company"":""Company S..."